version: '3.7'
services:
  nginx:
    container_name: koatuu-nginx
    image: nginx:latest
    working_dir: /var/www/app
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php

  php:
    container_name: koatuu-php
    build: docker
    working_dir: /var/www/app
    restart: always
    volumes:
      - ./docker/conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/app
    depends_on:
      - postgres

  postgres:
    container_name: koatuu-postgres
    image: postgres:alpine
    restart: always
    working_dir: /var/www/app
    environment:
      POSTGRES_DB: koatuu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
volumes:
  postgresql: